// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PracticaMvcTi.Models;

public partial class Empleado
{
    public int IdEmpleado { get; set; }

    public string Fotografia { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public int? Edad { get; set; }

    public int? IdDepartamento { get; set; }

    public int? IdPuesto { get; set; }

    public int? Salario { get; set; }

    public DateOnly? FechaDeNacimiento { get; set; }

    public DateOnly? FechaDeContratacion { get; set; }

    public string Direccion { get; set; }

    public string Telefono { get; set; }

    public string Correo { get; set; }

    public int? IdEstado { get; set; }

    public virtual Departamento IdDepartamentoNavigation { get; set; }

    public virtual Estado IdEstadoNavigation { get; set; }

    public virtual Puesto IdPuestoNavigation { get; set; }
}