// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PracticaMvcTi.Models;

public partial class Estado
{
    public int IdEstado { get; set; }

    public string NombreEstado { get; set; }
    public string Descripcion { get; set; }


    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();
}