// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace PracticaMvcTi.Models;

public partial class Puesto
{
    public int IdPuesto { get; set; }

    public int? IdDepartamento { get; set; }

    public string NombrePuesto { get; set; }

    public string Descripcion { get; set; }

    public virtual ICollection<Empleado> Empleados { get; set; } = new List<Empleado>();

    public virtual Departamento IdDepartamentoNavigation { get; set; }
}